# Generated by Django 4.2.29 on 2026-03-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuealert',
            name='co2_level',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='venuealert',
            name='hvac_airflow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venuealert',
            name='occupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venuealert',
            name='temperature',
            field=models.FloatField(default=22.0),
        ),
    ]
